name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: jerryis0812
          password: 59ebcd6d-5316-4935-a28b-b06b2b6d080d
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jerryis0812/cd0610:latest
