name: jerrytest0609
on: push

jobs:
  my-job:
    name: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3 
    - name: dependency
      run: |
        pip3 install -r requirements.txt
    - name: Run server 
      run: |
        python3 server.py > log.txt 2>&1 &
        pytest -vv
        
